export { EvidenceTab } from './TaskDetailEvidenceTab'
export { ResourcesTab } from './TaskDetailResourcesTab'
export { IssuesTab } from './TaskDetailIssuesTab'
export { LocksTab } from './TaskDetailLocksTab'
export { ObservabilityTab } from './TaskDetailObservabilityTab'
