export type ComponentGroup = 'Foundations' | 'Inputs' | 'Navigation' | 'Feedback' | 'Data' | 'Overlay'

export type DesignReviewStatus = 'pending-right-panel' | 'reviewed' | 'aligned' | 'design-node-missing'

export type ComponentSpec = {
  id: string
  name: string
  group: ComponentGroup
  antDesign: string
  states: string[]
  sizes: string[]
  variableBinding: string
  implementation: 'antd' | 'example-shell'
  designReview: DesignReviewStatus
  designNode: string
}

const names = [
  'Accordion', 'Alert', 'Alert Dialog', 'Aspect Ratio', 'Avatar', 'Badge', 'Breadcrumb', 'Button Group',
  'Calendar', 'Card', 'Carousel', 'Chart', 'Checkbox', 'Collapsible', 'Combobox', 'Command', 'Context Menu',
  'Data Table', 'Date Picker', 'Dialog', 'Direction', 'Drawer', 'Dropdown Menu', 'Empty', 'Field', 'Hover Card',
  'Input OTP', 'Input Group', 'Item', 'Kbd', 'Input', 'Label', 'Menubar', 'Navigation Menu', 'Pagination',
  'Popover', 'Progress', 'Radio Group', 'Resizable', 'Scroll Area', 'Select Menu', 'Separator', 'Sheet', 'Sidebar',
  'Skeleton', 'Slider', 'Spinner', 'Sonner', 'Switch', 'Table', 'Tabs', 'Textarea', 'Toggle', 'Toggle Group',
  'Tooltip', 'Typography', 'Utility Components', 'Tag', 'Tree', 'Rate', 'Popconfirm', 'Result', 'Back', 'Steps',
  'Comment', 'Transfer', 'Descriptions', 'Upload'
] as const

const antDesignMap: Record<string, string> = {
  'Alert Dialog': 'Modal', 'Aspect Ratio': 'example shell', 'Button Group': 'Space.Compact', Chart: 'example shell',
  Collapsible: 'Collapse', Combobox: 'AutoComplete', Command: 'example shell', 'Context Menu': 'Dropdown',
  'Data Table': 'Table', 'Date Picker': 'DatePicker', Dialog: 'Modal', Direction: 'ConfigProvider direction',
  'Dropdown Menu': 'Dropdown', Field: 'Form.Item', 'Hover Card': 'Popover', 'Input OTP': 'Input.OTP',
  'Input Group': 'Space.Compact', Item: 'List.Item', Kbd: 'Typography.Text', Menubar: 'Menu',
  'Navigation Menu': 'Menu', 'Radio Group': 'Radio.Group', Resizable: 'example shell', 'Scroll Area': 'example shell',
  'Select Menu': 'Select', Separator: 'Divider', Sheet: 'Drawer', Sidebar: 'example shell', Spinner: 'Spin',
  Sonner: 'example shell', Table: 'Table', Textarea: 'Input.TextArea', Toggle: 'Button', 'Toggle Group': 'Segmented',
  'Utility Components': 'Flex / Space', Back: 'Button', Comment: 'example shell'
}

const groups: Record<string, ComponentGroup> = {
  Accordion: 'Foundations', Alert: 'Feedback', 'Alert Dialog': 'Overlay', 'Aspect Ratio': 'Foundations', Avatar: 'Foundations', Badge: 'Feedback', Breadcrumb: 'Navigation', 'Button Group': 'Foundations', Calendar: 'Data', Card: 'Foundations', Carousel: 'Data', Chart: 'Data', Checkbox: 'Inputs', Collapsible: 'Foundations', Combobox: 'Inputs', Command: 'Navigation', 'Context Menu': 'Overlay', 'Data Table': 'Data', 'Date Picker': 'Inputs', Dialog: 'Overlay', Direction: 'Foundations', Drawer: 'Overlay', 'Dropdown Menu': 'Overlay', Empty: 'Feedback', Field: 'Inputs', 'Hover Card': 'Overlay', 'Input OTP': 'Inputs', 'Input Group': 'Inputs', Item: 'Foundations', Kbd: 'Foundations', Input: 'Inputs', Label: 'Inputs', Menubar: 'Navigation', 'Navigation Menu': 'Navigation', Pagination: 'Navigation', Popover: 'Overlay', Progress: 'Feedback', 'Radio Group': 'Inputs', Resizable: 'Foundations', 'Scroll Area': 'Foundations', 'Select Menu': 'Inputs', Separator: 'Foundations', Sheet: 'Overlay', Sidebar: 'Navigation', Skeleton: 'Feedback', Slider: 'Inputs', Spinner: 'Feedback', Sonner: 'Feedback', Switch: 'Inputs', Table: 'Data', Tabs: 'Navigation', Textarea: 'Inputs', Toggle: 'Inputs', 'Toggle Group': 'Inputs', Tooltip: 'Overlay', Typography: 'Foundations', 'Utility Components': 'Foundations', Tag: 'Feedback', Tree: 'Data', Rate: 'Inputs', Popconfirm: 'Overlay', Result: 'Feedback', Back: 'Navigation', Steps: 'Navigation', Comment: 'Data', Transfer: 'Inputs', Descriptions: 'Data', Upload: 'Inputs'
}

const inputStates = ['default', 'hover', 'focus', 'filled', 'disabled', 'error']

type FidelityProfile = Pick<ComponentSpec, 'states' | 'sizes' | 'variableBinding' | 'implementation' | 'designReview' | 'designNode'>

const reviewedProfiles: Record<string, FidelityProfile> = {
  Input: { states: ['default', 'hover', 'focus', 'filled', 'disabled', 'invalid'], sizes: ['small 24; middle 36; large 40; radius 5'], variableBinding: 'primary-white input background; text/default; border/1; ring/focus; error/default', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Input page：Variant Default·File·Password；State Default·Focus·Filled·Disabled·Invalid；右栏尺寸 2105×240、radius 5、gap 48/44；输入背景绑定 primary-white' },
  Avatar: { states: ['Type: Image', 'Fallback', 'Icon', 'Size: xl', 'lg', 'default', 'sm', 'xs', 'Fallback Text: CN', 'Show Badge: False'], sizes: ['W240 × H308 component set; 3 columns × 5 rows; radius 5'], variableBinding: 'purple/purple-4 stroke; primary/white; text/default; color/icon/context; radius 5', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Avatar page：右栏 Type Image/Fallback/Icon、Size xl/lg/default/sm/xs、Fallback Text CN、Show Badge False；选中组件集 W240×H308、3 columns × 5 rows、radius 5；nested Avatar Badge 与 IconPlaceholder；页面含 light/dark specimen' },
  Badge: { states: ['Variant: Default', 'Secondary', 'Outline', 'Destructive', 'Verified', 'Ghost', 'State: Default', 'Hover', 'Focus', 'Show Left Icon: False', 'Badge Text: Badge', 'Show Right Icon: False', 'number', 'dot', 'status', 'overflow'], sizes: ['component set W375 × H408; horizontal gap 49; vertical gap 44; radius 5'], variableBinding: 'purple/purple-4; text/default; fill/0; border/1; primary/white; status colors', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Badge page：Badge Number 与 Badge 两个 component set；Badge set 右栏 Variant Default/Secondary/Outline/Destructive/Verified/Ghost、State Default/Hover/Focus、Show Left Icon False、Badge Text Badge、Show Right Icon False；W375×H408、spacing 49/44、radius 5；selection colors +14' },
  Breadcrumb: { states: ['Size: md', 'sm', 'Items (md): 1 item', 'Items (sm): 1 item', 'default', 'with icon', 'collapsed', 'current'], sizes: ['selected component W713 × H143; radius 5; vertical gap 43'], variableBinding: 'text/default; text/description; color/icon/context; border/1', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Breadcrumb page：右栏 Size md/sm、Items (md)/(sm) 1 item；选中组件 W713×H143、radius 5、vertical gap 43；按路径、图标、折叠和当前项展示' },
  'Button Group': { states: ['orientation horizontal', 'orientation vertical', 'variant outline', 'variant default', 'variant secondary'], sizes: ['W1402 × H353 component set; 6 items; radius 5'], variableBinding: 'primary; primary/white; fill/5; border/1; text/default', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Button Group page：Properties Orientation Horizontal/Vertical、Variant Outline/Default/Secondary、Items 6；组件集 W1402×H353、radius 5、selection colors +5' },
  Calendar: { states: ['Content (Arrow + With Month and Year Dropdown): 1 item', 'Content (Month): 1 item', 'week numbers', 'custom cell size', 'date and time picker', 'presets'], sizes: ['W244 × H280; padding 8; gap 16; radius 16'], variableBinding: 'primary/white; border/1; border-width/border; primary; text/description', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Calendar page：右栏 Content (Arrow + With Month and Year Dropdown) 1 item、Content (Month) 1 item；选中组件 W244×H280、padding 8、gap 16、radius 16；fill primary/white、border/1、border width 1' },
  Card: { states: ['Size: default', 'sm', 'Show Image: False', 'Card Header: True', 'Show Action: False', 'Swap Action: Button', 'Card Title: Title Text', 'Card Description', 'Card Content: 2 items', 'Card Footer: 2 items'], sizes: ['W468 × H566; radius 5; padding 24'], variableBinding: 'primary-white; fill/0; border/1; text/default; text/description', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Card page：右栏 Size default/sm、Show Image False、Card Header True、Show Action False、Swap Action Button、Card Title Title Text、Card Description、Card Content 2 items、Card Footer 2 items；W468×H566、radius 5' },
  Carousel: { states: ['orientation horizontal', 'orientation vertical', 'breakpoint lg', 'breakpoint md', 'breakpoint sm'], sizes: ['W504 × H1896; 5 CarouselItems; radius 5'], variableBinding: 'purple/purple-4 stroke; primary; primary/white; border/1; fill/0', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Carousel page：Properties Orientation Horizontal/Vertical、Breakpoint lg/md/sm、CarouselItems Wrapper 5 items；组件集 W504×H1896、radius 5、purple/purple-4 stroke' },
  Chart: { states: ['bar', 'line', 'area', 'pie', 'radial'], sizes: ['representative chart frame W371.71 × H572; radius 0'], variableBinding: 'selection color #9747FF; primary; success/default; error/default; no frame stroke', implementation: 'example-shell', designReview: 'aligned', designNode: 'Figma Chart page：Charts / Components 为自定义 frame；代表 frame 右栏 W371.71×H572、radius 0、selection color #9747FF；无直接 AntD 图表组件，example 内实现展示外壳' },
  Checkbox: { states: ['Checked: No', 'Checked: Yes', 'State: Default', 'Focus', 'Disabled', 'Pressed', 'Invalid', 'Type: Default', 'Type: Box'], sizes: ['control height 36; radius 5'], variableBinding: 'primary; primary/white; border/1; error/default; text/default', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Checkbox page：右栏 Properties Checked No/Yes、State Default/Focus/Disabled/Pressed/Invalid、Type Default/Box；control token 与语义色绑定' },
  Collapsible: { states: ['active', 'inactive'], sizes: ['W382 × H301; padding 16; radius 5'], variableBinding: 'purple/purple-4 stroke; text/default; color/icon/context; border/1; fill/0', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Collapsible page：Properties State Active/Inactive；右栏 W382×H301、padding 16、radius 5，stroke 绑定 purple/purple-4' },
  Combobox: { states: ['default', 'focus', 'filled', 'disabled', 'error'], sizes: ['small 24; middle 36; large 40; radius 5'], variableBinding: 'primary-white; border/1; ring/focus; text/default; text/description', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Combobox page：输入/选择复合状态；背景绑定 primary-white，focus ring 使用 focus token' },
  Command: { states: ['default', 'search', 'keyboard shortcut', 'empty'], sizes: ['W480 shell; radius 5; row 36'], variableBinding: 'fill/0; primary-white; border/1; text/default; text/description', implementation: 'example-shell', designReview: 'aligned', designNode: 'Figma Command page：搜索、命令行、shortcut、empty 外壳；当前主题单组渲染' },
  'Context Menu': { states: ['Active: Yes', 'Active: No', 'SubTrigger Text', 'default', 'hover', 'destructive', 'disabled'], sizes: ['menu row 36; radius 5; padding 4'], variableBinding: 'fill/0; primary-white; border/1; text/default; color/icon/context; error/default', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Context Menu page：右栏 Properties Active Yes/No、SubTrigger Text；菜单项 hover、destructive、disabled；Dropdown overlay 使用 semantic surface/border' },
  'Data Table': { states: ['Header', 'Content', 'Footer', 'hover row', 'selected row', 'sort', 'pagination'], sizes: ['W724 × H369; compact row 36; radius 0'], variableBinding: 'fill/0; primary-white; border/1; primary/white; text/default; text/description; color/icon/context', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Data Table page：右栏 Properties Header/Content/Footer；选中 frame W724×H369、radius 0；表头、行 hover、选中、排序、分页；AntD Table 适配 semantic vars' },
  'Date Picker': { states: ['State: Default', 'Hover', 'Focus', 'Active', 'Disabled', 'Type: Icon Left', 'With Input', 'Icon Right', 'Show Icon: True'], sizes: ['small 24; middle 36; large 40; radius 5'], variableBinding: 'primary-white; border/1; ring/focus; text/default; error/default', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Date Picker page：右栏 Properties State Default/Hover/Focus/Active/Disabled、Type Icon Left/With Input/Icon Right、Show Icon True；输入框背景 primary-white，边框 border/1' },
  Dialog: { states: ['Title Text: Dialog title', 'Description Text: This is a dialog description.', 'Show Close Button: True', 'Dialog Content: 1 item', 'Dialog Footer: 1 item', 'default', 'confirm', 'destructive', 'loading'], sizes: ['default 384; small 320; radius 16'], variableBinding: 'primary/white; border/1; fill/0; text/default; fill/5; alpha/50', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Dialog page：右栏 Title Text Dialog title、Description Text、Show Close Button True、Dialog Content/Footer 1 item；Modal variants；surface、footer alpha、action fill/5 按当前主题映射' },
  Direction: { states: ['ltr', 'rtl'], sizes: ['responsive; control height 36'], variableBinding: 'text/default; border/1; primary', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Direction page 当前 Layers 仅有 Direction Auto layout frame，未暴露 Components 子节点或右栏组件 Properties；需设计侧补充可选中的组件节点后再核验' },
  Drawer: { states: ['Direction: bottom', 'top', 'right', 'left', 'Show Header: True', 'Title Text', 'Description Text'], sizes: ['width 378; radius 0/16'], variableBinding: 'fill/0; primary-white; border/1; text/default; alpha/50', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Drawer page：右栏 Properties Direction bottom/top/right/left、Show Header True、Title Text、Description Text；左右抽屉、footer、loading；Drawer overlay 语义变量' },
  'Dropdown Menu': { states: ['Active: No', 'Active: Yes', 'Show Icon: False', 'SubTrigger Text', 'default', 'hover', 'submenu', 'destructive', 'disabled'], sizes: ['menu row 36; radius 5; padding 4'], variableBinding: 'primary-white; fill/0; border/1; text/default; color/icon/context; error/default', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Dropdown Menu page：右栏 Properties Active No/Yes、Show Icon False、SubTrigger Text；Dropdown menu states 使用 AntD Dropdown overlay' },
  Empty: { states: ['Type: Icon', 'Avatar', 'AvatarGroup', 'simple', 'with action'], sizes: ['W320 shell; radius 5'], variableBinding: 'fill/1; fill/0; color/icon/context; text/description; primary; border/1', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Empty page：右栏 Type Icon/Avatar/AvatarGroup，nested IconPlaceholder/Avatar/Avatar Group；空状态 icon/text/action 语义绑定' },
  Field: { states: ['Orientation: Vertical', 'Responsive', 'Data Invalid: False', 'True', 'Description Placement: Under Input', 'Under Label'], sizes: ['label 20; control 36; gap 8; radius 5'], variableBinding: 'text/default; text/description; error/default; primary-white; border/1', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Field page：右栏 Orientation Vertical/Responsive、Data Invalid False/True、Description Placement Under Input/Under Label；Form field label、help、error、required' },
  'Hover Card': { states: ['State: Default', 'Hover', 'Focus', 'Disabled', 'Pressed', 'Trigger Text'], sizes: ['popover 320; radius 5; padding 16'], variableBinding: 'fill/5; primary/white; primary-white; border/1; text/default; text/description', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Hover Card page：右栏 State Default/Hover/Focus/Disabled/Pressed、Trigger Text；Popover surface 使用 primary-white/border/1' },
  'Input OTP': { states: ['State: Default', 'Focus', 'Filled', 'Invalid', 'Disabled'], sizes: ['4 cells × 36; gap 8; radius 5'], variableBinding: 'primary/white; border/1; text/default; primary/focus; error/default', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Input OTP page：右栏 State Default/Focus/Filled/Invalid/Disabled；多格输入绑定 primary/white、border/1、primary/focus、error/default' },
  'Input Group': { states: ['Type: Input', 'Textarea', 'State: Default', 'Focus', 'Filled', 'Disabled', 'Invalid', 'Placeholder Text'], sizes: ['control height 36; radius 5; gap 0'], variableBinding: 'primary-white; border/1; text/default; color/icon/context; fill/1; primary/focus; error/default', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Input Group page：右栏 Type Input/Textarea、State Default/Focus/Filled/Disabled/Invalid、Placeholder Text；Space.Compact' },
  Item: { states: ['Variant: Icon', 'Image', 'Icon (Simple)', 'AvatarGroup', 'Avatar'], sizes: ['row 36/48; radius 5'], variableBinding: 'fill/1; fill/0; color/icon/context; border/1; text/default; text/description', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Item page：右栏 Variant Icon/Image/Icon (Simple)/AvatarGroup/Avatar，nested IconPlaceholder；列表行 default/hover/selected/disabled；List.Item 适配' },
  Kbd: { states: ['Background: Default', 'Primary', 'Show Left Icon: False', 'Text: Ctrl', 'Show Right Icon'], sizes: ['height 24; radius 5; padding 6'], variableBinding: 'fill/0; fill/1; border/1; text/default; text/description; custom background alpha', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Kbd page：右栏 Background Default/Primary、Show Left Icon False、Text Ctrl、Show Right Icon；键帽与 shortcut 文本' },
  Label: { states: ['default', 'required', 'disabled', 'error'], sizes: ['line 20; gap 8'], variableBinding: 'text/default; text/description; error/default', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Label page 当前 Layers 仅有 Label Auto layout frame，未暴露 Components 子节点或右栏组件 Properties；需设计侧补充可选中的组件节点后再核验' },
  Menubar: { states: ['default', 'hover', 'active', 'disabled', 'Item / Separator'], sizes: ['height 40; radius 5; item gap 4'], variableBinding: 'fill/0; primary; primary/white; text/default; border/1', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Menubar page：右栏读取 Item / Separator；horizontal menu states；AntD Menu horizontal' },
  'Navigation Menu': { states: ['Variant: Trigger', 'Link', 'State: Default', 'Hover', 'Focused', 'Navigation Text: Menu Item', 'submenu', 'disabled'], sizes: ['height 40; radius 5'], variableBinding: 'fill/0; primary; primary/white; text/default; border/1; purple/purple-4', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Navigation Menu page：右栏 Variant Trigger/Link、State Default/Hover/Focused、Navigation Text Menu Item；导航项、active、submenu；AntD Menu' },
  Pagination: { states: ['Variant: Previous', 'Next', 'Link', 'Ellipsis', 'State: Default', 'Hover', 'Focus', 'Active', 'Active (Hover)', 'Active (Focus)', 'Disabled', 'Number Text: 1'], sizes: ['item 36; gap 8; radius 5'], variableBinding: 'primary; primary/white; border/1; text/default; text/description', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Pagination page：右栏 Variant Previous/Next/Link/Ellipsis、State Default/Hover/Focus/Active/Active (Hover)/Active (Focus)/Disabled、Number Text 1；AntD Pagination' },
  Popover: { states: ['Show Header: True', 'Show Title: True', 'Title Text: Dimensions', 'Show Description: True', 'rest', 'hover', 'focus', 'with arrow'], sizes: ['popover 320; radius 5; padding 16'], variableBinding: 'primary-white; border/1; text/default; text/description', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Popover page：右栏 Show Header/Title/Description True、Title Text Dimensions；Popover surface、arrow、placement；AntD Popover' },
  Progress: { states: ['Percent: 100%', '75%', '50%', '25%', '0%', 'line', 'circle', 'success', 'error', 'indeterminate'], sizes: ['line 8; circle 72; radius 999'], variableBinding: 'purple/purple-4; fill/5; alpha/20; success/default; error/default', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Progress page：右栏 Percent 100/75/50/25/0；purple/purple-4、fill/5、alpha/20 变量；AntD Progress' },
  'Radio Group': { states: ['Items: 1 item', 'default', 'checked', 'disabled', 'error'], sizes: ['control 36; gap 12; radius 5'], variableBinding: 'primary; primary/white; border/1; error/default; text/default', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Radio Group page：右栏 Items 1 item；radio group states；AntD Radio.Group' },
  Resizable: { states: ['Panel 2: 1 item', 'Panel 1: 1 item', 'default', 'horizontal', 'vertical'], sizes: ['panel responsive; handle 8; radius 5'], variableBinding: 'fill/0; border/1; text/default; primary; text/description', implementation: 'example-shell', designReview: 'aligned', designNode: 'Figma Resizable page：右栏 Panel 2/Panel 1；split panel 与 resize handle；example 外壳绑定 border/1/primary' },
  'Scroll Area': { states: ['Vertical', 'Horizontal', 'default', 'overflow'], sizes: ['viewport 320 × 180; radius 5'], variableBinding: 'primary/white; border/1; fill/0; text/default; text/description', implementation: 'example-shell', designReview: 'aligned', designNode: 'Figma Scroll Area page：右栏 Vertical component 与 primary/white、border/1；viewport、overflow、scrollbar；example 外壳' },
  'Select Menu': { states: ['Label Text: Select Label', 'default', 'open', 'selected', 'disabled', 'error'], sizes: ['small 24; middle 36; large 40; radius 5'], variableBinding: 'primary-white; border/1; primary; text/default; text/description; error/default', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Select Menu page：右栏 Label Text Select Label 及 text/description；选择器状态；AntD Select' },
  Separator: { states: ['Orientation: Horizontal', 'Vertical'], sizes: ['1px; gap 16'], variableBinding: 'border/1; primary', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Separator page：右栏 Orientation Horizontal/Vertical，border/1；Divider 使用 border/1' },
  Sheet: { states: ['Close Icon / State: Default', 'Hover', 'Focus', 'default', 'left', 'right', 'bottom'], sizes: ['drawer 378; radius 0/16'], variableBinding: 'fill/0; primary-white; border/1; alpha/50; text/default; color/icon/context; primary/focus', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Sheet page：右栏 Close Icon State Default/Hover/Focus；侧滑 panel variants；Drawer 外壳' },
  Sidebar: { states: ['Submenu: False', 'True', 'expanded', 'collapsed', 'active item'], sizes: ['width 240/64; radius 0/5'], variableBinding: 'fill/0; fill/1; primary; primary/white; border/1; text/default; color/icon/context', implementation: 'example-shell', designReview: 'aligned', designNode: 'Figma Sidebar page：右栏 SidebarMenuItem Submenu False/True、nested SidebarMenuButton/SidebarMenuSub；expanded/collapsed/active；example 导航外壳' },
  Skeleton: { states: ['Variant: Default', 'Card', 'Text', 'Form', 'Table', 'active', 'avatar', 'paragraph'], sizes: ['line 16; gap 8; radius 5'], variableBinding: 'fill/1; fill/2; border/1', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Skeleton page：右栏 Variant Default/Card/Text/Form/Table；paragraph、avatar、active shimmer；AntD Skeleton' },
  Slider: { states: ['State: Default', 'Hover', 'Focus', 'range', 'disabled', 'with tooltip'], sizes: ['track 4; handle 16; radius 999'], variableBinding: 'primary; primary/white; primary/focus; fill/1; border/1', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Slider page：右栏 State Default/Hover/Focus、single/range/disabled/tooltip；AntD Slider' },
  Spinner: { states: ['Size: 8', '6', '5', '4', '3', 'Spin Degree: 0', '90', '180', '270'], sizes: ['16/24/32; radius 999'], variableBinding: 'primary; primary/white; fill/0; color/icon/context', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Spinner page：右栏 Size 8/6/5/4/3、Spin Degree 0/90/180/270、IconPlaceholder；AntD Spin' },
  Sonner: { states: ['Action / Type: Default', 'Secondary', 'default', 'success', 'error', 'warning', 'action'], sizes: ['toast 360 × hug; radius 12; padding 16'], variableBinding: 'primary-white; border/1; text/default; success/default; error/default; alpha/50; purple/purple-4', implementation: 'example-shell', designReview: 'aligned', designNode: 'Figma Sonner page：右栏 Action Type Default/Secondary、purple/purple-4；toast variants；example 内展示当前主题单组' },
  Switch: { states: ['Items: 1 item', 'unchecked', 'checked', 'disabled', 'loading'], sizes: ['small 24; middle 36; radius 999'], variableBinding: 'primary; primary/white; fill/1; border/1; text/description', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Switch page：右栏 Items 1 item；checked/unchecked/disabled/loading；AntD Switch' },
  Table: { states: ['Variant: Default', 'Button', 'State: Default', 'Hover', 'Show Text: True', 'Text: Head Text'], sizes: ['row 36; radius 5'], variableBinding: 'primary-white; fill/0; border/1; primary; text/default', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Table page：右栏 Variant Default/Button、State Default/Hover、Show Text True、Text Head Text；表头、hover、selected、bordered、compact；AntD Table' },
  Tabs: { states: ['Variant: Default', 'Line', 'Orientation: Default', 'Vertical', 'Items: 3 items', 'line', 'card', 'active', 'disabled'], sizes: ['height 36/44; radius 5'], variableBinding: 'primary; primary/white; border/1; text/default; text/description', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Tabs page：右栏 Variant Default/Line、Orientation Default/Vertical、Items 3 items；line/card/active/disabled；AntD Tabs' },
  Textarea: { states: ['State: Default', 'Filled', 'Focus', 'Disabled', 'Error', 'Error (Focus)', 'Placeholder Text'], sizes: ['W320; min H96; radius 5'], variableBinding: 'primary-white; border/1; ring/focus; text/default; error/default', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Textarea page：右栏 State Default/Filled/Focus/Disabled/Error/Error (Focus)、Placeholder Text；Input.TextArea' },
  Toggle: { states: ['Variant: Default', 'Outline', 'Size: Default', 'sm', 'lg', 'State: Default', 'Hover', 'Focus', 'Pressed', 'Disabled', 'Show Icon: True'], sizes: ['height 36; radius 5'], variableBinding: 'fill/1; primary; primary/white; border/1; text/default', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Toggle page：右栏 Variant Default/Outline、Size Default/sm/lg、State Default/Hover/Focus/Pressed/Disabled、Show Icon True；Button 语义映射' },
  'Toggle Group': { states: ['Type: Default', 'Fill', 'With Spacing', 'Orientation: Horizontal', 'Vertical', 'Items: 5 items', 'single', 'multiple', 'pressed', 'disabled'], sizes: ['height 36; gap 0; radius 5'], variableBinding: 'fill/0; primary; primary/white; border/1; text/default; color/icon/context', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Toggle Group page：右栏 Type Default/Fill/With Spacing、Orientation Horizontal/Vertical、Items 5 items；共享边框与圆角' },
  Tooltip: { states: ['Side: Top', 'Bottom', 'Left', 'Right', 'Tooltip Text: This is a tooltip', 'Show KdbGroup: False', 'hover', 'focus'], sizes: ['tooltip hug; radius 5; padding 8'], variableBinding: 'purple/purple-4; fill/5; primary/white; text/default; alpha/50', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Tooltip page：右栏 Side Top/Bottom/Left/Right、Tooltip Text、Show KdbGroup False；placement、hover、focus；AntD Tooltip' },
  Typography: { states: ['H2', 'Text: This is heading 2', 'title', 'body', 'description', 'code', 'keyboard'], sizes: ['type scale per foundation; line height semantic'], variableBinding: 'primary/white; border/1; text/default; color/icon/context', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Typography page：右栏 H2、Text This is heading 2；标题、正文、辅助文字、code、keyboard；Typography' },
  'Utility Components': { states: ['_Chart / Card', 'Slot', 'Footer Text', 'Footer Descripion Text', 'Icon: AreaChart', 'Flex', 'Space', 'Watermark', 'FloatButton'], sizes: ['responsive; gap 8/16/24'], variableBinding: 'fill/0; border/1; text/default; text/description; color/icon/context; purple/purple-4', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Utility Components page：右栏 _Chart / Card、Slot、Footer Text、Footer Descripion Text、Icon AreaChart；布局与辅助组件' },
  Tag: { states: ['尺寸: 大', '中', '小', '迷你', '颜色: 默认', '浪漫红', '仙野绿', '碧涛青', '活力橙', '晚秋红', '黄昏', '青春紫', '品红', '极致蓝', '海蔚蓝', '填充: true/false', '边框: false/true'], sizes: ['height 24; radius 5; padding 8'], variableBinding: 'fill/1; border/1; text/default; primary/white; status palettes', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Tag page：右栏 尺寸大/中/小/迷你、颜色全量 palette、填充 true/false、边框 false/true；AntD Tag' },
  Tree: { states: ['default', 'expanded', 'selected', 'disabled', 'checkable'], sizes: ['row 36; indent 24; radius 5'], variableBinding: 'primary; primary/white; border/1; text/default; text/description; color/icon/context', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Tree page：右栏 Tree 主体仅提供 color/icon/context、text/default；树节点展开/选中/禁用/checkable；AntD Tree' },
  Rate: { states: ['default', 'half', 'clear', 'disabled'], sizes: ['star 20; gap 4'], variableBinding: 'primary; fill/1; text/description', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Rate page：右栏未暴露额外 properties；评分、半星、清除、禁用；AntD Rate' },
  Popconfirm: { states: ['Property 1: 上左', '上', '上右', '下右', '下', '下左', '左上', '左', '左下', '右上', '右', '右下', 'destructive', 'loading'], sizes: ['popover 320; radius 5; padding 16'], variableBinding: 'primary-white; border/1; text/default; error/default; fill/5', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Popconfirm page：右栏 Property 1 全量 placement；确认、destructive、loading；AntD Popconfirm' },
  Result: { states: ['Property 1: 成功提示', '信息提示', '警告提示', '错误提示', '404'], sizes: ['W480; radius 5; padding 24'], variableBinding: 'fill/0; primary; success/default; error/default; text/description', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Result page：右栏 Property 1 成功/信息/警告/错误提示；success/error/warning/info/404；AntD Result' },
  Back: { states: ['Property 1: Default', 'hover', 'disabled'], sizes: ['button 36; radius 5'], variableBinding: 'primary; primary/white; border/1; text/default', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Back page：右栏 Property 1 Default/hover；返回按钮；AntD Button' },
  Steps: { states: ['状态: 完成', '进行中', '等待', '错误', 'vertical'], sizes: ['step 36; gap 24; radius 5'], variableBinding: 'primary; primary/white; success/default; error/default; text/description', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Steps page：右栏 steps-item-icon 状态 完成/进行中/等待/错误、IconPlaceholder；wait/process/finish/error/vertical；AntD Steps' },
  Comment: { states: ['时间对齐: 左', '右', '操作对齐: 左', '右', '显示头像: True', '显示时间: True', 'default', 'nested', 'actions', 'loading'], sizes: ['W480; radius 5; padding 16'], variableBinding: 'primary-white; border/1; text/default; text/description', implementation: 'example-shell', designReview: 'aligned', designNode: 'Figma Comment page：右栏 时间对齐/操作对齐 左右、显示头像/时间 True；评论内容、操作、嵌套；example card 外壳' },
  Transfer: { states: ['模式: 标准', '单向', '简单', '显示搜索: True', '显示底部: True', 'default', 'search', 'selected', 'disabled'], sizes: ['list 280 × 320; gap 16; radius 5'], variableBinding: 'primary-white; fill/0; border/1; primary; text/default', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Transfer page：右栏 模式 标准/单向/简单、显示搜索 True、显示底部 True；双栏穿梭、搜索、selected、disabled；AntD Transfer' },
  Descriptions: { states: ['Property 1: Huge', 'Large', 'Medium', 'Mini', 'Small', 'default', 'bordered', 'vertical', 'responsive'], sizes: ['row 36; radius 5; padding 16'], variableBinding: 'primary-white; fill/0; border/1; text/default; text/description', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Descriptions page：右栏 header Property 1 Huge/Large/Medium/Mini/Small；描述列表 bordered/vertical/responsive；AntD Descriptions' },
  Upload: { states: ['状态: 默认', '上传中', '错误', 'default', 'drag', 'success', 'disabled'], sizes: ['dropzone W480 × H180; radius 5'], variableBinding: 'primary-white; fill/0; border/1; primary; error/default; success/default', implementation: 'antd', designReview: 'aligned', designNode: 'Figma Upload page：右栏 file-list-item 状态 默认/上传中/错误；点击/拖拽、uploading、success、error、disabled；AntD Upload' },
}

const rightPanelVerified = new Set(['Input', 'Avatar', 'Badge', 'Breadcrumb', 'Button Group', 'Calendar', 'Card', 'Carousel', 'Chart', 'Checkbox', 'Combobox', 'Command', 'Context Menu', 'Data Table', 'Collapsible', 'Date Picker', 'Dialog', 'Drawer', 'Dropdown Menu', 'Empty', 'Field', 'Hover Card', 'Input OTP', 'Input Group', 'Item', 'Kbd', 'Menubar', 'Navigation Menu', 'Pagination', 'Popover', 'Progress', 'Radio Group', 'Resizable', 'Scroll Area', 'Select Menu', 'Separator', 'Sheet', 'Sidebar', 'Skeleton', 'Slider', 'Spinner', 'Sonner', 'Switch', 'Table', 'Tabs', 'Textarea', 'Toggle', 'Toggle Group', 'Tooltip', 'Typography', 'Utility Components', 'Tag', 'Tree', 'Rate', 'Popconfirm', 'Result', 'Back', 'Steps', 'Comment', 'Transfer', 'Descriptions', 'Upload'])
const strictlyAligned = new Set(['Accordion', 'Alert', 'Alert Dialog', 'Aspect Ratio', 'Avatar', 'Badge', 'Breadcrumb', 'Button Group', 'Calendar', 'Card', 'Carousel', 'Chart', 'Checkbox', 'Collapsible', 'Combobox', 'Command', 'Context Menu', 'Data Table', 'Date Picker', 'Dialog', 'Drawer', 'Dropdown Menu', 'Empty', 'Field', 'Hover Card', 'Input OTP', 'Input Group', 'Item', 'Kbd', 'Input', 'Menubar', 'Navigation Menu', 'Pagination', 'Popover', 'Progress', 'Radio Group', 'Resizable', 'Scroll Area', 'Select Menu', 'Separator', 'Sheet', 'Sidebar', 'Skeleton', 'Slider', 'Spinner', 'Sonner', 'Switch', 'Table', 'Tabs', 'Textarea', 'Toggle', 'Toggle Group', 'Tooltip', 'Typography', 'Utility Components', 'Tag', 'Tree', 'Rate', 'Popconfirm', 'Result', 'Back', 'Steps', 'Comment', 'Transfer', 'Descriptions', 'Upload'])
const designNodeMissing = new Set(['Direction', 'Label'])

export const componentRegistry: ComponentSpec[] = names.map((name) => ({
  id: name.toLowerCase().replace(/[^a-z0-9]+/g, '-'),
  name,
  group: groups[name],
  antDesign: antDesignMap[name] ?? name,
  states: reviewedProfiles[name]?.states ?? (name === 'Input' ? inputStates : name === 'Accordion'
    ? ['borderless expanded', 'borderless collapsed', 'disabled item', 'bordered General', 'bordered Subscription & Billing']
    : name === 'Alert'
      ? ['default', 'without icon', 'error', 'success', 'info', 'warning', 'action: Undo', 'action: Enable', 'theme follows current site mode']
    : name === 'Alert Dialog'
      ? ['Size default × Destructive No', 'Size default × Destructive Yes', 'Size sm × Destructive No', 'Size sm × Destructive Yes', 'theme follows current site mode']
    : name === 'Aspect Ratio'
      ? ['Ratio: 1/1', '4/3', '3/4', '5/4', '4/5', '3/2', '2/3', '16/10', '10/16', '16/9', '9/16', '2/1', '1/2', '1.618/1', '1/1.618', '21/9', '9/21', 'theme follows current site mode']
      : ['default', 'hover', 'disabled']),
  sizes: reviewedProfiles[name]?.sizes ?? (name === 'Input' ? ['small', 'middle', 'large'] : name === 'Accordion'
    ? ['hug width; 0 gap root frame; four specimen layouts']
    : name === 'Alert'
      ? ['W634 × H64 Hug; gap 8; padding 10/8; radius 12; preview gap 64; preview padding 16/128; radius 20']
    : name === 'Alert Dialog'
      ? ['default: W384 × H194/196; sm: W320 × H250; radius 16; light + dark']
    : name === 'Aspect Ratio'
      ? ['ratio variants W240 × ratio-derived H; radius 0; component set W288; vertical gap 48; page gap 64; padding-top/bottom 128']
    : ['design-defined; right panel pending']),
  variableBinding: reviewedProfiles[name]?.variableBinding ?? (name === 'Input'
    ? 'primary-white → input background; text-default; border-1; ring focus'
    : name === 'Accordion'
      ? 'text/default; color/icon/context; border/1; fill/0 (#F7F8FA) page surface'
      : name === 'Alert'
        ? 'primary/white; border/1; text/default; text/description; color/icon/context; error/default; custom amber warning palette; fill/0 page surface'
      : name === 'Alert Dialog'
        ? 'fill/0; border/1; primary/white; text/default; text/description; color/icon/context; fill/1; fill/5; alpha/50; error/default; custom/destructive\\10 dark:destructive\\20; alpha/10'
      : name === 'Aspect Ratio'
        ? 'image fill per variant; page fill/0; border/1 frame; no component stroke; radius 0'
      : 'pending right-panel variable read'),
  implementation: reviewedProfiles[name]?.implementation ?? (antDesignMap[name] === 'example shell' ? 'example-shell' : 'antd'),
  designReview: strictlyAligned.has(name) ? 'aligned' : designNodeMissing.has(name) ? 'design-node-missing' : rightPanelVerified.has(name) ? 'reviewed' : 'pending-right-panel',
  designNode: reviewedProfiles[name]?.designNode ?? (name === 'Input'
    ? 'Figma Components / Input：Variant Default·File·Password；State Default·Focus·Filled·Disabled·Invalid；Placeholder Text'
    : name === 'Accordion'
      ? 'Figma Accordion page node 17031-160654：borderless + bordered specimens；page fill/0 = #F7F8FA；right-panel selection colors'
      : name === 'Alert'
        ? 'Figma Alert page：Light / Dark 预览；本站按当前主题单组渲染；13 个 Alert 实例；W634×H64、padding 10/8、gap 8、rounded-lg；页面 fill/0、border/1、rounded-2xl'
      : name === 'Alert Dialog'
        ? 'Figma Alert Dialog page：Light/Dark 纵向预览；本站按当前主题单组渲染；页面 W1536×H3780、gap 64、padding-top/bottom 128；4 variants (Size default/sm × Destructive No/Yes)；default W384×H194/196；sm W320×H250；组件集 W864×H522、gap 48/40'
      : name === 'Aspect Ratio'
        ? 'Figma Aspect Ratio page：Light/Dark 预览各含 1/1 与 4/3；本站按当前主题单组渲染；页面 W1536×H3780、gap 64、padding-top/bottom 128；组件集 Ratio 17 variants，W288×H5463.18、gap 48；变体 W240，H 按比例，Image fill'
      : 'Figma File component page (right-panel read pending)')
}))

export const componentGroups: ComponentGroup[] = ['Foundations', 'Inputs', 'Navigation', 'Feedback', 'Data', 'Overlay']

export function getComponent(id: string): ComponentSpec {
  return componentRegistry.find((item) => item.id === id) ?? componentRegistry[0]
}
